// Code generated by MockGen. DO NOT EDIT.
// Source: ./steppers.go

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Mockhoge is a mock of hoge interface.
type Mockhoge struct {
	ctrl     *gomock.Controller
	recorder *MockhogeMockRecorder
}

// MockhogeMockRecorder is the mock recorder for Mockhoge.
type MockhogeMockRecorder struct {
	mock *Mockhoge
}

// NewMockhoge creates a new mock instance.
func NewMockhoge(ctrl *gomock.Controller) *Mockhoge {
	mock := &Mockhoge{ctrl: ctrl}
	mock.recorder = &MockhogeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhoge) EXPECT() *MockhogeMockRecorder {
	return m.recorder
}

// hogehoge mocks base method.
func (m *Mockhoge) hogehoge() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "hogehoge")
}

// hogehoge indicates an expected call of hogehoge.
func (mr *MockhogeMockRecorder) hogehoge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "hogehoge", reflect.TypeOf((*Mockhoge)(nil).hogehoge))
}
