---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-simulation-kube-scheduler-simulator-x-k8s-io-v1alpha1-scenario
  failurePolicy: Fail
  name: mscenario.kb.io
  rules:
  - apiGroups:
    - simulation.kube-scheduler-simulator.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scenarios
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-simulation-kube-scheduler-simulator-x-k8s-io-v1alpha1-scenario
  failurePolicy: Fail
  name: vscenario.kb.io
  rules:
  - apiGroups:
    - simulation.kube-scheduler-simulator.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scenarios
  sideEffects: None
